/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as PortalPolicyRouteImport } from './routes/_portal/policy'
import { Route as PortalDashboardRouteImport } from './routes/_portal/dashboard'
import { Route as PortalAdminRouteImport } from './routes/_portal/admin'
import { Route as PortalStatusEnterRouteImport } from './routes/_portal/status/enter'
import { Route as PortalStatusCheckRouteImport } from './routes/_portal/status/check'
import { Route as PortalLeavesAttendanceRouteImport } from './routes/_portal/leaves/attendance'
import { Route as PortalLeavesApplicationRouteImport } from './routes/_portal/leaves/application'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPolicyRoute = PortalPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatusEnterRoute = PortalStatusEnterRouteImport.update({
  id: '/status/enter',
  path: '/status/enter',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatusCheckRoute = PortalStatusCheckRouteImport.update({
  id: '/status/check',
  path: '/status/check',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeavesAttendanceRoute = PortalLeavesAttendanceRouteImport.update({
  id: '/leaves/attendance',
  path: '/leaves/attendance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeavesApplicationRoute = PortalLeavesApplicationRouteImport.update({
  id: '/leaves/application',
  path: '/leaves/application',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof PortalAdminRoute
  '/dashboard': typeof PortalDashboardRoute
  '/policy': typeof PortalPolicyRoute
  '/leaves/application': typeof PortalLeavesApplicationRoute
  '/leaves/attendance': typeof PortalLeavesAttendanceRoute
  '/status/check': typeof PortalStatusCheckRoute
  '/status/enter': typeof PortalStatusEnterRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof PortalAdminRoute
  '/dashboard': typeof PortalDashboardRoute
  '/policy': typeof PortalPolicyRoute
  '/': typeof PortalIndexRoute
  '/leaves/application': typeof PortalLeavesApplicationRoute
  '/leaves/attendance': typeof PortalLeavesAttendanceRoute
  '/status/check': typeof PortalStatusCheckRoute
  '/status/enter': typeof PortalStatusEnterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_portal/admin': typeof PortalAdminRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/policy': typeof PortalPolicyRoute
  '/_portal/': typeof PortalIndexRoute
  '/_portal/leaves/application': typeof PortalLeavesApplicationRoute
  '/_portal/leaves/attendance': typeof PortalLeavesAttendanceRoute
  '/_portal/status/check': typeof PortalStatusCheckRoute
  '/_portal/status/enter': typeof PortalStatusEnterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/policy'
    | '/leaves/application'
    | '/leaves/attendance'
    | '/status/check'
    | '/status/enter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/policy'
    | '/'
    | '/leaves/application'
    | '/leaves/attendance'
    | '/status/check'
    | '/status/enter'
  id:
    | '__root__'
    | '/_portal'
    | '/login'
    | '/signup'
    | '/_portal/admin'
    | '/_portal/dashboard'
    | '/_portal/policy'
    | '/_portal/'
    | '/_portal/leaves/application'
    | '/_portal/leaves/attendance'
    | '/_portal/status/check'
    | '/_portal/status/enter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/policy': {
      id: '/_portal/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PortalPolicyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin': {
      id: '/_portal/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/status/enter': {
      id: '/_portal/status/enter'
      path: '/status/enter'
      fullPath: '/status/enter'
      preLoaderRoute: typeof PortalStatusEnterRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/status/check': {
      id: '/_portal/status/check'
      path: '/status/check'
      fullPath: '/status/check'
      preLoaderRoute: typeof PortalStatusCheckRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/leaves/attendance': {
      id: '/_portal/leaves/attendance'
      path: '/leaves/attendance'
      fullPath: '/leaves/attendance'
      preLoaderRoute: typeof PortalLeavesAttendanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/leaves/application': {
      id: '/_portal/leaves/application'
      path: '/leaves/application'
      fullPath: '/leaves/application'
      preLoaderRoute: typeof PortalLeavesApplicationRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalPolicyRoute: typeof PortalPolicyRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalLeavesApplicationRoute: typeof PortalLeavesApplicationRoute
  PortalLeavesAttendanceRoute: typeof PortalLeavesAttendanceRoute
  PortalStatusCheckRoute: typeof PortalStatusCheckRoute
  PortalStatusEnterRoute: typeof PortalStatusEnterRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalPolicyRoute: PortalPolicyRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalLeavesApplicationRoute: PortalLeavesApplicationRoute,
  PortalLeavesAttendanceRoute: PortalLeavesAttendanceRoute,
  PortalStatusCheckRoute: PortalStatusCheckRoute,
  PortalStatusEnterRoute: PortalStatusEnterRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
